// lib/data.ts

export interface AITool {
  id: string;
  name: string;
  description: string;
  tagline: string;
  logo: string;
  category: string[];
  rating: number;
  reviewCount: number;
  websiteUrl: string;
  videoUrl?: string; 
  features: string[];
  pricing: string;
}

export const categories = [
  'Copywriting',
  'Coding',
  'Design',
  'Marketing',
  'Video Editing',
  'Data Analysis',
  'Customer Support',
  'Project Management',
  'Content Creation'
];

export const aiTools: AITool[] = [
  {
    id: '1',
    name: 'ChatGPT',
    tagline: 'Conversational AI for writing and problem-solving',
    description: 'ChatGPT is an advanced conversational AI model developed by OpenAI that can engage in natural dialogue, answer questions, generate creative content, write code, and assist with various tasks across multiple domains.',
    logo: '🤖',
    category: ['Copywriting', 'Coding', 'Content Creation'],
    rating: 4.8,
    reviewCount: 12453,
    websiteUrl: 'https://chat.openai.com',
    videoUrl: 'https://www.youtube.com/embed/jvqFAi7vkBc',
    features: ['Natural language understanding', 'Code generation and debugging', 'Multi-language support'],
    pricing: 'Free / $20 per month for Plus'
  },
  {
    id: '2',
    name: 'Midjourney',
    tagline: 'AI art generation from text descriptions',
    description: 'Midjourney is an AI-powered tool that generates high-quality images from textual descriptions. Perfect for designers, artists, and creators looking to bring their visual ideas to life quickly.',
    logo: '🎨',
    category: ['Design', 'Content Creation'],
    rating: 4.7,
    reviewCount: 8921,
    websiteUrl: 'https://midjourney.com',
    videoUrl: 'https://www.youtube.com/embed/xR2zBq37jB4',
    features: ['Text-to-image generation', 'Style variations', 'High-resolution outputs'],
    pricing: 'Starting at $10/month'
  },
  {
    id: '3',
    name: 'GitHub Copilot',
    tagline: 'AI pair programmer for faster coding',
    description: 'GitHub Copilot is an AI coding assistant that helps developers write code faster by suggesting whole lines or blocks of code as you type.',
    logo: '💻',
    category: ['Coding'],
    rating: 4.6,
    reviewCount: 5432,
    websiteUrl: 'https://github.com/features/copilot',
    videoUrl: 'https://www.youtube.com/embed/Fi3JAOJuNME',
    features: ['Code completion', 'Multi-language support', 'IDE integration'],
    pricing: '$10/month for individuals'
  },
  {
    id: '4',
    name: 'Jasper AI',
    tagline: 'AI content platform for marketing teams',
    description: 'Jasper AI is a powerful content creation tool designed for marketing teams. Generate blog posts, social media content, emails, and more.',
    logo: '✍️',
    category: ['Copywriting', 'Marketing', 'Content Creation'],
    rating: 4.5,
    reviewCount: 3210,
    websiteUrl: 'https://jasper.ai',
    videoUrl: 'https://www.youtube.com/embed/n30Y2tqR-v0',
    features: ['Long-form content', 'SEO optimization', 'Brand voice customization'],
    pricing: 'Starting at $39/month'
  },
  {
    id: '5',
    name: 'Runway ML',
    tagline: 'AI-powered video editing and generation',
    description: 'Runway ML brings AI-powered creative tools to video editing. Generate, edit, and transform videos with cutting-edge machine learning models.',
    logo: '🎬',
    category: ['Video Editing', 'Content Creation'],
    rating: 4.7,
    reviewCount: 2891,
    websiteUrl: 'https://runwayml.com',
    videoUrl: 'https://www.youtube.com/embed/zH3b2g-P92U',
    features: ['Video generation', 'Background removal', 'Text-to-video'],
    pricing: 'Free tier / Paid plans from $12/month'
  },
  {
    id: '6',
    name: 'Tableau AI',
    tagline: 'Smart data visualization and analytics',
    description: 'Tableau AI combines powerful data visualization with AI-driven insights to help you understand your data better and make informed decisions.',
    logo: '📊',
    category: ['Data Analysis'],
    rating: 4.4,
    reviewCount: 1567,
    websiteUrl: 'https://tableau.com',
    videoUrl: 'https://www.youtube.com/embed/QwbP4g94wT4',
    features: ['Automated insights', 'Natural language queries', 'Predictive analytics'],
    pricing: 'Contact for pricing'
  },
  {
    id: '7',
    name: 'Intercom AI',
    tagline: 'AI-powered customer support automation',
    description: 'Intercom AI helps businesses provide better customer support through intelligent automation, chatbots, and personalized messaging.',
    logo: '💬',
    category: ['Customer Support'],
    rating: 4.5,
    reviewCount: 4123,
    websiteUrl: 'https://intercom.com',
    videoUrl: 'https://www.youtube.com/embed/1Bntw3_XfEw',
    features: ['AI chatbots', 'Ticket automation', 'Customer insights'],
    pricing: 'Starting at $74/month'
  },
  {
    id: '8',
    name: 'Notion AI',
    tagline: 'AI writing assistant for your workspace',
    description: 'Notion AI is integrated directly into Notion, helping you write, brainstorm, edit, and summarize content without leaving your workspace.',
    logo: '📝',
    category: ['Project Management', 'Copywriting', 'Content Creation'],
    rating: 4.6,
    reviewCount: 6789,
    websiteUrl: 'https://notion.so',
    videoUrl: 'https://www.youtube.com/embed/Z91t8n1_44Y',
    features: ['Writing assistance', 'Summarization', 'Action items extraction'],
    pricing: '$10/month add-on'
  },
  {
    id: '9',
    name: 'Canva AI',
    tagline: 'Design made simple with AI assistance',
    description: 'Canva AI brings intelligent design features to the popular design platform, making professional design accessible to everyone.',
    logo: '🎨',
    category: ['Design', 'Marketing', 'Content Creation'],
    rating: 4.7,
    reviewCount: 9234,
    websiteUrl: 'https://canva.com',
    videoUrl: 'https://www.youtube.com/embed/39v2xS13038',
    features: ['Magic Design', 'Background remover', 'Text-to-image'],
    pricing: 'Free / Pro from $12.99/month'
  },
  {
    id: '10',
    name: 'Grammarly',
    tagline: 'AI-powered writing assistant',
    description: 'Grammarly uses AI to help you write clear, mistake-free content across all your apps and websites. Beyond grammar, it offers style, tone, and clarity suggestions.',
    logo: '✅',
    category: ['Copywriting', 'Content Creation'],
    rating: 4.6,
    reviewCount: 15678,
    websiteUrl: 'https://grammarly.com',
    videoUrl: 'https://www.youtube.com/embed/p112R_9QkXk',
    features: ['Grammar checking', 'Tone detection', 'Clarity suggestions'],
    pricing: 'Free / Premium from $12/month'
  },
  { 
    id: "11", 
    name: "Copy.ai", 
    tagline: "AI-powered GTM automation platform",
    logo: "📋",
    category: ["Copywriting", "Marketing"],
    description: "Copy.ai is an advanced platform that helps sales and marketing teams automate their Go-To-Market workflows, from drafting personalized emails to generating full SEO content strategies.",
    rating: 4.5,
    reviewCount: 3840,
    websiteUrl: "https://copy.ai",
    videoUrl: "https://www.youtube.com/embed/w7iA7vT_GvA",
    features: ["Workflow automation", "Brand voice integration", "90+ writing tools"],
    pricing: "Free / Pro from $36/month"
  },
  {
    id: '12',
    name: 'Descript',
    tagline: 'Edit video by editing text',
    description: 'Descript revolutionizes video editing by allowing you to edit video content as easily as editing a text document, powered by AI.',
    logo: '🎥',
    category: ['Video Editing', 'Content Creation'],
    rating: 4.6,
    reviewCount: 3421,
    websiteUrl: 'https://descript.com',
    videoUrl: 'https://www.youtube.com/embed/U25qf6mXU-Y',
    features: ['Transcription', 'Text-based editing', 'Voice cloning'],
    pricing: 'Free / Paid from $12/month'
  },
  {
    id: '13',
    name: 'Claude 3.5 Sonnet',
    tagline: 'Advanced reasoning and coding assistant',
    description: 'Claude 3.5 Sonnet is Anthropic\'s most powerful model to date, excelling at complex reasoning, nuance, and high-level coding tasks with a human-like touch.',
    logo: '🎭',
    category: ['Coding', 'Copywriting', 'Content Creation'],
    rating: 4.9,
    reviewCount: 7240,
    websiteUrl: 'https://claude.ai',
    videoUrl: 'https://www.youtube.com/embed/RtfAGuK5n0M',
    features: ['Artifacts live preview', 'Advanced reasoning', '200k context window'],
    pricing: 'Free / $20 per month for Pro'
  },
  {
    id: '14',
    name: 'Cursor',
    tagline: 'The AI code editor built for engineers',
    description: 'Cursor is an AI-native code editor that inherits everything you love about VS Code but adds deep AI integration for refactoring, bug hunting, and building from scratch.',
    logo: '🚀',
    category: ['Coding'],
    rating: 4.8,
    reviewCount: 3120,
    websiteUrl: 'https://cursor.com',
    videoUrl: 'https://www.youtube.com/embed/5F_fJ98hL4w',
    features: ['Codebase-wide chat', 'AI-powered refactoring', 'Privacy-first indexing'],
    pricing: 'Free / $20 per month Pro'
  },
  {
    id: '15',
    name: 'Perplexity AI',
    tagline: 'AI search engine with real-time citations',
    description: 'Perplexity is a conversational search engine that provides direct, cited answers to queries using real-time web access and multiple LLMs.',
    logo: '🌐',
    category: ['Data Analysis', 'Content Creation'],
    rating: 4.7,
    reviewCount: 5890,
    websiteUrl: 'https://perplexity.ai',
    videoUrl: 'https://www.youtube.com/embed/WJ1U2M0_2j8',
    features: ['Real-time search', 'Source citations', 'Pro discovery mode'],
    pricing: 'Free / $20 per month Pro'
  },
  {
    id: '16',
    name: 'ElevenLabs',
    tagline: 'High-fidelity AI voice and speech synthesis',
    description: 'ElevenLabs provides the most lifelike AI voice technology, allowing users to generate high-quality speech in dozens of languages and clone their own voices.',
    logo: '🎙️',
    category: ['Video Editing', 'Content Creation'],
    rating: 4.8,
    reviewCount: 4230,
    websiteUrl: 'https://elevenlabs.io',
    videoUrl: 'https://www.youtube.com/embed/rQn_I_U1zGE',
    features: ['Voice cloning', 'Multilingual synthesis', 'Emotional control'],
    pricing: 'Free / Paid from $5/month'
  },
  {
    id: '17',
    name: 'Asana AI',
    tagline: 'Smart project management and workflow automation',
    description: 'Asana AI helps teams manage projects by automating routine tasks, predicting bottlenecks, and providing smart status updates.',
    logo: '📌',
    category: ['Project Management'],
    rating: 4.5,
    reviewCount: 12400,
    websiteUrl: 'https://asana.com',
    videoUrl: 'https://www.youtube.com/embed/g6H1vS9yT4I',
    features: ['Smart status reporting', 'Workflow automation', 'Goal tracking'],
    pricing: 'Free / Paid from $10.99/month'
  },
  { 
    id: "18", 
    name: "Leonardo.ai", 
    tagline: "Generative AI for creative production",
    logo: "🦁",
    category: ["Design", "Content Creation"],
    description: "Leonardo.ai provides a powerful suite of generative AI tools for creating production-quality assets, game textures, and character designs with granular control over style and consistency.",
    rating: 4.8,
    reviewCount: 5420,
    websiteUrl: "https://leonardo.ai",
    videoUrl: "https://www.youtube.com/embed/T4X1K7-7ZgA",
    features: ["AI Canvas for outpainting", "Fine-tuned model selection", "Image-to-image generation"],
    pricing: "Free / Paid plans from $10/month"
  },
  { 
    id: "19", 
    name: "Replit Agent", 
    tagline: "Build full-stack apps through conversation",
    logo: "🌀",
    category: ["Coding"],
    description: "Replit Agent is a breakthrough AI coding assistant that can build, deploy, and manage full-stack applications on your behalf just by following your natural language instructions.",
    rating: 4.9,
    reviewCount: 2150,
    websiteUrl: "https://replit.com",
    videoUrl: "https://www.youtube.com/embed/Q4X-P6w2wWk",
    features: ["Autonomous app building", "Integrated database setup", "Instant deployment"],
    pricing: "Included in Replit Core ($15/month)"
  },
  { 
    id: "20", 
    name: "Suno AI", 
    tagline: "The most realistic AI music generator",
    logo: "🎵",
    category: ["Content Creation"],
    description: "Suno AI allows anyone to create full, high-quality songs—including lyrics, melody, and realistic vocals—in almost any genre or language from a simple text prompt.",
    rating: 4.7,
    reviewCount: 4670,
    websiteUrl: "https://suno.com",
    videoUrl: "https://www.youtube.com/embed/Fz1qN2vM_6s",
    features: ["Full song generation", "Custom lyric input", "Vocal and instrumental modes"],
    pricing: "Free / Pro from $8/month"
  },
  {
    id: '21',
    name: 'Vercel v0',
    tagline: 'Generative UI built by Vercel',
    description: 'v0 uses AI to generate copy-and-paste React components using Tailwind CSS from simple text prompts. Perfect for rapid prototyping and Next.js developers.',
    logo: '⚡',
    category: ['Coding', 'Design'],
    rating: 4.8,
    reviewCount: 4150,
    websiteUrl: 'https://v0.dev',
    videoUrl: 'https://www.youtube.com/embed/39v2xS13038',
    features: ['React & Tailwind output', 'Iterative chat editing', 'Shadcn/UI integration'],
    pricing: 'Free / Premium from $20/month'
  },
  {
    id: '22',
    name: 'Synthesia',
    tagline: 'AI video generation with digital avatars',
    description: 'Synthesia allows you to create professional videos with lifelike AI avatars and voiceovers in over 120 languages, just by typing text. No cameras or actors required.',
    logo: '👤',
    category: ['Video Editing', 'Marketing', 'Content Creation'],
    rating: 4.7,
    reviewCount: 8120,
    websiteUrl: 'https://synthesia.io',
    videoUrl: 'https://www.youtube.com/embed/aZ5aIebhBnw',
    features: ['140+ AI Avatars', '120+ Languages', 'Custom avatar cloning'],
    pricing: 'Starting at $22/month'
  },
  {
    id: '23',
    name: 'Gamma',
    tagline: 'A new medium for presenting ideas',
    description: 'Gamma uses AI to generate beautiful, engaging presentations, webpages, and documents in seconds. Say goodbye to slide formatting and focus on your content.',
    logo: '🪄',
    category: ['Design', 'Content Creation'],
    rating: 4.8,
    reviewCount: 5630,
    websiteUrl: 'https://gamma.app',
    videoUrl: 'https://www.youtube.com/embed/1Bntw3_XfEw',
    features: ['One-click themes', 'Interactive embeds', 'Analytics tracking'],
    pricing: 'Free / Plus from $8/month'
  },
  {
    id: '24',
    name: 'Gemini Advanced',
    tagline: 'Google\'s most capable AI model',
    description: 'Powered by Gemini 1.5 Pro, this multimodal AI excels at highly complex tasks, including analyzing massive datasets, understanding huge codebases, and deep logical reasoning.',
    logo: '✨',
    category: ['Coding', 'Data Analysis', 'Copywriting'],
    rating: 4.8,
    reviewCount: 15400,
    websiteUrl: 'https://gemini.google.com/advanced',
    videoUrl: 'https://www.youtube.com/embed/VihlsMOzEAw',
    features: ['1M token context window', 'Google Workspace integration', 'Advanced data analysis'],
    pricing: '$20/month (Google One AI Premium)'
  },
  {
    id: '25',
    name: 'Taskade AI',
    tagline: 'AI agents for team productivity',
    description: 'Taskade combines task management, notes, and mind maps with autonomous AI agents that can research, plan, and execute tasks for your team 24/7.',
    logo: '✅',
    category: ['Project Management'],
    rating: 4.6,
    reviewCount: 2980,
    websiteUrl: 'https://taskade.com',
    videoUrl: 'https://www.youtube.com/embed/xR2zBq37jB4',
    features: ['Autonomous AI agents', 'Mind map generation', 'Real-time collaboration'],
    pricing: 'Free / Paid from $4/month'
  },
  {
    id: '26',
    name: 'Framer AI',
    tagline: 'Design and publish sites instantly',
    description: 'Framer AI lets you generate stunning, fully responsive websites from a single text prompt. Tweak color palettes and typography instantly with AI assistance.',
    logo: '🖼️',
    category: ['Design', 'Coding'],
    rating: 4.7,
    reviewCount: 6120,
    websiteUrl: 'https://framer.com',
    videoUrl: 'https://www.youtube.com/embed/5F_fJ98hL4w',
    features: ['Text-to-website', 'Instant localization', 'Built-in CMS'],
    pricing: 'Free / Paid from $15/month'
  },
  {
    id: '27',
    name: 'Chatbase',
    tagline: 'Custom ChatGPT for your website',
    description: 'Chatbase allows you to train an AI chatbot on your own data (documents, website links, Notion) and embed it on your website as a customer support widget.',
    logo: '💬',
    category: ['Customer Support'],
    rating: 4.8,
    reviewCount: 3450,
    websiteUrl: 'https://chatbase.co',
    videoUrl: 'https://www.youtube.com/embed/rQn_I_U1zGE',
    features: ['Custom data training', 'Website embedding', 'Lead generation'],
    pricing: 'Free / Paid from $19/month'
  },
  {
    id: '28',
    name: 'Codeium',
    tagline: 'Free AI code acceleration toolkit',
    description: 'Codeium is a powerful, free alternative to GitHub Copilot that offers blazing-fast autocomplete, integrated chat, and codebase-aware context in over 40 editors.',
    logo: '👨‍💻',
    category: ['Coding'],
    rating: 4.9,
    reviewCount: 8900,
    websiteUrl: 'https://codeium.com',
    videoUrl: 'https://www.youtube.com/embed/Fi3JAOJuNME',
    features: ['Unlimited autocomplete', 'Codebase context', 'Enterprise privacy'],
    pricing: 'Free for individuals'
  },
  {
    id: '29',
    name: 'HeyGen',
    tagline: 'AI video generation for business',
    description: 'Create engaging business and marketing videos with studio-quality AI avatars and voices. HeyGen excels at generating personalized sales videos at scale.',
    logo: '🎥',
    category: ['Video Editing', 'Marketing'],
    rating: 4.7,
    reviewCount: 4210,
    websiteUrl: 'https://heygen.com',
    videoUrl: 'https://www.youtube.com/embed/zH3b2g-P92U',
    features: ['Personalized video scale', 'Studio-quality avatars', 'API integration'],
    pricing: 'Free / Creator from $24/month'
  },
  {
    id: '30',
    name: 'Luma Dream Machine',
    tagline: 'High-quality AI video generation',
    description: 'Luma Dream Machine is a next-generation AI model capable of generating highly realistic, cinematic 5-second video clips directly from text or image prompts.',
    logo: '🌌',
    category: ['Video Editing', 'Design'],
    rating: 4.8,
    reviewCount: 3100,
    websiteUrl: 'https://lumalabs.ai/dream-machine',
    videoUrl: 'https://www.youtube.com/embed/U25qf6mXU-Y',
    features: ['Text-to-video', 'Image-to-video', 'Cinematic camera controls'],
    pricing: 'Free tier / Paid from $29/month'
  }
];